services:
  - type: cron
    name: stochastic-bot
    schedule: "*/5 * * * *"
    runtime: python
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TWELVE_API_KEY
        sync: false
    buildCommand: ""
    startCommand: "python main.py"
